export 'dart:convert';
export 'dart:async';
export 'dart:io';
export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:flutter/widgets.dart';
export 'package:academy/main.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:dropdown_button2/dropdown_button2.dart';
export 'package:image_picker/image_picker.dart';
export 'package:intl/date_symbol_data_local.dart'; // โหลดข้อมูล locale สำหรับการแสดงวันที่
export 'package:permission_handler/permission_handler.dart';
export 'package:file_picker/file_picker.dart';
export 'package:path_provider/path_provider.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:loading_animation_widget/loading_animation_widget.dart';
export 'package:awesome_bottom_bar/awesome_bottom_bar.dart';
export 'package:awesome_bottom_bar/widgets/inspired/inspired.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:video_player/video_player.dart';
export 'package:flutter_advanced_switch/flutter_advanced_switch.dart';
export 'package:syncfusion_flutter_calendar/calendar.dart';
export 'package:percent_indicator/percent_indicator.dart';
export 'package:flutter_switch/flutter_switch.dart';
export 'package:multi_select_flutter/multi_select_flutter.dart';
export 'package:open_file/open_file.dart';
export 'package:flutter_speed_dial/flutter_speed_dial.dart';
export 'package:flutter_custom_clippers/flutter_custom_clippers.dart';
export 'package:hive_flutter/hive_flutter.dart';
export 'package:academy/welcome_to_academy/academy/academy.dart';
export 'package:academy/welcome_to_academy/export.dart';
// export 'package:tab_indicator_styler/tab_indicator_styler.dart';
export 'package:quickalert/quickalert.dart';
// export 'package:flutter_carousel_widget/flutter_carousel_widget.dart';
// export 'package:auto_size_text/auto_size_text.dart';
// export 'package:flutter_side_menu/flutter_side_menu.dart';
export 'package:academy/welcome_to_academy/language/translate.dart';
// export 'package:google_mlkit_barcode_scanning/google_mlkit_barcode_scanning.dart';
export 'package:animated_custom_dropdown/custom_dropdown.dart';
